const DataPenerbangan = [
  [
    "Bandung",
    "Lampung",
    "Jawa",
    "Bali",
    "Aceh",
    "Jakarta",
    "Kalimantan",
    "Maluku",
    "Banten",
    "Palembang",
  ],
  [
    "Lampung",
    "Bandung",
    "Palembang",
    "Jawa",
    "Kalimantan",
    "Maluku",
    "Banten",
    "Jakarta",
    "Bali",
    "Aceh",
  ],
  [
    "1 Januari 2022",
    "1 Januari 2022",
    "18 Januari 2022",
    "18 Januari 2022",
    "21 Januari 2022",
    "21 Januari 2022",
  ],
  [
    "Elang Air",
    "Wings Air",
    "Majapahit Air",
    "Elang Air",
    "Wings Air",
    "Majapahit Air",
    "Wings Air",
    "Elang Air",
    "Wings Air",
    "Majapahit Air",
  ],
];

export default DataPenerbangan;
